name: hello
version: 2.10.42
summary: GNU Hello, the "hello world" snap
description: GNU hello prints a friendly greeting.
  This is part of the snapcraft tour at https://snapcraft.io/
confinement: strict

apps:
  hello:
    command: hello -g \"Hello, snap guru!\"
  universe:
    command: hello -g \"Hello, universe!\"

parts:
  gnu-hello:
    plugin: autotools
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz

